application: thomasoropeza-resume
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /
  script: main.app
- url: /photo
  script: main.app
- url: /assets
  static_dir: assets
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest